/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import { GetEmployeeDto } from "../model/GetEmployeeDto";

/**
* Employee service.
* @module api/EmployeeApi
* @version v1
*/
export class EmployeeApi {
  /**
    * Constructs a new EmployeeApi. 
    * @alias module:api/EmployeeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
     * Callback function to receive the result of the apiEmployeeByEmailGet operation.
     * @callback moduleapi/EmployeeApi~apiEmployeeByEmailGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetEmployeeDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.email 
     * @param {module:api/EmployeeApi~apiEmployeeByEmailGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  apiEmployeeByEmailGet(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      email: opts["email"]
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["text/plain", "application/json", "text/json"];
    let returnType = GetEmployeeDto;

    return this.apiClient.callApi(
      "/api/Employee/by/email",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiEmployeeDelete operation.
     * @callback moduleapi/EmployeeApi~apiEmployeeDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.email 
     * @param {module:api/EmployeeApi~apiEmployeeDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiEmployeeDelete(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      email: opts["email"]
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/Employee",
      "DELETE",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiEmployeeGet operation.
     * @callback moduleapi/EmployeeApi~apiEmployeeGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetEmployeeDto>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:api/EmployeeApi~apiEmployeeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  apiEmployeeGet(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["text/plain", "application/json", "text/json"];
    let returnType = [GetEmployeeDto];

    return this.apiClient.callApi(
      "/api/Employee",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiEmployeePost operation.
     * @callback moduleapi/EmployeeApi~apiEmployeePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {module:model/PostEmployeeDto} opts.body 
     * @param {module:api/EmployeeApi~apiEmployeePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiEmployeePost(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = opts["body"];

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/json", "text/json", "application/_*+json"];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/Employee",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiEmployeePut operation.
     * @callback moduleapi/EmployeeApi~apiEmployeePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {module:model/PutEmployeeDto} opts.body 
     * @param {module:api/EmployeeApi~apiEmployeePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiEmployeePut(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = opts["body"];

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/json", "text/json", "application/_*+json"];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/Employee",
      "PUT",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
}
