/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import { GetUserDto } from "../model/GetUserDto";

/**
* User service.
* @module api/UserApi
* @version v1
*/
export class UserApi {
  /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
     * Callback function to receive the result of the apiUserByEmailGet operation.
     * @callback moduleapi/UserApi~apiUserByEmailGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetUserDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.email 
     * @param {module:api/UserApi~apiUserByEmailGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  apiUserByEmailGet(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      email: opts["email"]
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["text/plain", "application/json", "text/json"];
    let returnType = GetUserDto;

    return this.apiClient.callApi(
      "/api/User/by/email",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiUserDelete operation.
     * @callback moduleapi/UserApi~apiUserDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.email 
     * @param {module:api/UserApi~apiUserDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiUserDelete(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      email: opts["email"]
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/User",
      "DELETE",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiUserGet operation.
     * @callback moduleapi/UserApi~apiUserGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetUserDto>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {module:api/UserApi~apiUserGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
  apiUserGet(opts, callbackRequest, callback, setErrorMess, setOpenErrorAlert) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["text/plain", "application/json", "text/json"];
    let returnType = [GetUserDto];

    return this.apiClient.callApi(
      "/api/User",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiUserPost operation.
     * @callback moduleapi/UserApi~apiUserPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {module:model/PostUserDto} opts.body 
     * @param {module:api/UserApi~apiUserPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiUserPost(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    opts = opts || {};
    let postBody = opts["body"];

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/json", "text/json", "application/_*+json"];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/User",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  apiUserNotAddedEmpGet(
    opts,
    callbackRequest,
    callback,
    setErrorMess,
    setOpenErrorAlert
  ) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["text/plain", "application/json", "text/json"];
    let returnType = [GetUserDto];

    return this.apiClient.callApi(
      "/api/User/not/added/emp",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
  /**
     * Callback function to receive the result of the apiUserPut operation.
     * @callback moduleapi/UserApi~apiUserPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

  /**
     * @param {Object} opts Optional parameters
     * @param {module:model/PutUserDto} opts.body 
     * @param {module:api/UserApi~apiUserPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
  apiUserPut(opts, callbackRequest, callback, setErrorMess, setOpenErrorAlert) {
    opts = opts || {};
    let postBody = opts["body"];

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = ["application/json", "text/json", "application/_*+json"];
    let accepts = [];
    let returnType = null;

    return this.apiClient.callApi(
      "/api/User",
      "PUT",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callbackRequest,
      callback,
      setErrorMess,
      setOpenErrorAlert
    );
  }
}
