/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEmployeeDto model module.
 * @module model/GetEmployeeDto
 * @version v1
 */
export class GetEmployeeDto {
  /**
   * Constructs a new <code>GetEmployeeDto</code>.
   * @alias module:model/GetEmployeeDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEmployeeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEmployeeDto} obj Optional instance to populate.
   * @return {module:model/GetEmployeeDto} The populated <code>GetEmployeeDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEmployeeDto();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('positionName'))
        obj.positionName = ApiClient.convertToType(data['positionName'], 'String');
      if (data.hasOwnProperty('roleName'))
        obj.roleName = ApiClient.convertToType(data['roleName'], 'String');
      if (data.hasOwnProperty('startWorkDate'))
        obj.startWorkDate = ApiClient.convertToType(data['startWorkDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
GetEmployeeDto.prototype.email = undefined;

/**
 * @member {String} address
 */
GetEmployeeDto.prototype.address = undefined;

/**
 * @member {String} positionName
 */
GetEmployeeDto.prototype.positionName = undefined;

/**
 * @member {String} roleName
 */
GetEmployeeDto.prototype.roleName = undefined;

/**
 * @member {Date} startWorkDate
 */
GetEmployeeDto.prototype.startWorkDate = undefined;

