/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetUserDto model module.
 * @module model/GetUserDto
 * @version v1
 */
export class GetUserDto {
  /**
   * Constructs a new <code>GetUserDto</code>.
   * @alias module:model/GetUserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUserDto} obj Optional instance to populate.
   * @return {module:model/GetUserDto} The populated <code>GetUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetUserDto();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('roleName'))
        obj.roleName = ApiClient.convertToType(data['roleName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
GetUserDto.prototype.email = undefined;

/**
 * @member {String} roleName
 */
GetUserDto.prototype.roleName = undefined;

