/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The PutPositionDto model module.
 * @module model/PutPositionDto
 * @version v1
 */
export class PutPositionDto {
  /**
   * Constructs a new <code>PutPositionDto</code>.
   * @alias module:model/PutPositionDto
   * @class
   * @param name {String} 
   * @param description {String} 
   */
  constructor(name, description, newName) {
    this.name = name;
    this.description = description;
    this.newName = newName;
  }

  /**
   * Constructs a <code>PutPositionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutPositionDto} obj Optional instance to populate.
   * @return {module:model/PutPositionDto} The populated <code>PutPositionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutPositionDto();
      if (data.hasOwnProperty("name"))
        obj.name = ApiClient.convertToType(data["name"], "String");
      if (data.hasOwnProperty("newName"))
        obj.newName = ApiClient.convertToType(data["newName"], "String");
      if (data.hasOwnProperty("description"))
        obj.description = ApiClient.convertToType(
          data["description"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PutPositionDto.prototype.name = undefined;

/**
 * @member {String} newName
 */
PutPositionDto.prototype.newName = undefined;

/**
 * @member {String} description
 */
PutPositionDto.prototype.description = undefined;
