/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PutRoleDto model module.
 * @module model/PutRoleDto
 * @version v1
 */
export class PutRoleDto {
  /**
   * Constructs a new <code>PutRoleDto</code>.
   * @alias module:model/PutRoleDto
   * @class
   * @param roleName {String} 
   * @param newRoleName {String} 
   */
  constructor(roleName, newRoleName) {
    this.roleName = roleName;
    this.newRoleName = newRoleName;
  }

  /**
   * Constructs a <code>PutRoleDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutRoleDto} obj Optional instance to populate.
   * @return {module:model/PutRoleDto} The populated <code>PutRoleDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutRoleDto();
      if (data.hasOwnProperty('roleName'))
        obj.roleName = ApiClient.convertToType(data['roleName'], 'String');
      if (data.hasOwnProperty('newRoleName'))
        obj.newRoleName = ApiClient.convertToType(data['newRoleName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} roleName
 */
PutRoleDto.prototype.roleName = undefined;

/**
 * @member {String} newRoleName
 */
PutRoleDto.prototype.newRoleName = undefined;

