/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The PutUserDto model module.
 * @module model/PutUserDto
 * @version v1
 */
export class PutUserDto {
  /**
   * Constructs a new <code>PutUserDto</code>.
   * @alias module:model/PutUserDto
   * @class
   * @param email {String} 
   * @param roleName {String} 
   */
  constructor(email, roleName, password) {
    this.email = email;
    this.roleName = roleName;
    this.password = password;
  }

  /**
   * Constructs a <code>PutUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutUserDto} obj Optional instance to populate.
   * @return {module:model/PutUserDto} The populated <code>PutUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutUserDto();
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
      if (data.hasOwnProperty("password"))
        obj.password = ApiClient.convertToType(data["password"], "String");
      if (data.hasOwnProperty("roleName"))
        obj.roleName = ApiClient.convertToType(data["roleName"], "String");
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
PutUserDto.prototype.email = undefined;

/**
 * @member {String} password
 */
PutUserDto.prototype.password = undefined;

/**
 * @member {String} roleName
 */
PutUserDto.prototype.roleName = undefined;
