/*
 * BackEnd
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AuthDto} from './model/AuthDto';
import {GetEmployeeDto} from './model/GetEmployeeDto';
import {GetPositionDto} from './model/GetPositionDto';
import {GetRoleDto} from './model/GetRoleDto';
import {GetUserDto} from './model/GetUserDto';
import {PostEmployeeDto} from './model/PostEmployeeDto';
import {PostPositionDto} from './model/PostPositionDto';
import {PostRoleDto} from './model/PostRoleDto';
import {PostUserDto} from './model/PostUserDto';
import {PutEmployeeDto} from './model/PutEmployeeDto';
import {PutPositionDto} from './model/PutPositionDto';
import {PutRoleDto} from './model/PutRoleDto';
import {PutUserDto} from './model/PutUserDto';
import {AuthApi} from './api/AuthApi';
import {EmployeeApi} from './api/EmployeeApi';
import {PositionApi} from './api/PositionApi';
import {ReportApi} from './api/ReportApi';
import {RoleApi} from './api/RoleApi';
import {UserApi} from './api/UserApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BackEnd = require('index'); // See note below*.
* var xxxSvc = new BackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BackEnd.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BackEnd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthDto model constructor.
     * @property {module:model/AuthDto}
     */
    AuthDto,

    /**
     * The GetEmployeeDto model constructor.
     * @property {module:model/GetEmployeeDto}
     */
    GetEmployeeDto,

    /**
     * The GetPositionDto model constructor.
     * @property {module:model/GetPositionDto}
     */
    GetPositionDto,

    /**
     * The GetRoleDto model constructor.
     * @property {module:model/GetRoleDto}
     */
    GetRoleDto,

    /**
     * The GetUserDto model constructor.
     * @property {module:model/GetUserDto}
     */
    GetUserDto,

    /**
     * The PostEmployeeDto model constructor.
     * @property {module:model/PostEmployeeDto}
     */
    PostEmployeeDto,

    /**
     * The PostPositionDto model constructor.
     * @property {module:model/PostPositionDto}
     */
    PostPositionDto,

    /**
     * The PostRoleDto model constructor.
     * @property {module:model/PostRoleDto}
     */
    PostRoleDto,

    /**
     * The PostUserDto model constructor.
     * @property {module:model/PostUserDto}
     */
    PostUserDto,

    /**
     * The PutEmployeeDto model constructor.
     * @property {module:model/PutEmployeeDto}
     */
    PutEmployeeDto,

    /**
     * The PutPositionDto model constructor.
     * @property {module:model/PutPositionDto}
     */
    PutPositionDto,

    /**
     * The PutRoleDto model constructor.
     * @property {module:model/PutRoleDto}
     */
    PutRoleDto,

    /**
     * The PutUserDto model constructor.
     * @property {module:model/PutUserDto}
     */
    PutUserDto,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The EmployeeApi service constructor.
    * @property {module:api/EmployeeApi}
    */
    EmployeeApi,

    /**
    * The PositionApi service constructor.
    * @property {module:api/PositionApi}
    */
    PositionApi,

    /**
    * The ReportApi service constructor.
    * @property {module:api/ReportApi}
    */
    ReportApi,

    /**
    * The RoleApi service constructor.
    * @property {module:api/RoleApi}
    */
    RoleApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
